### ISSUE TITLE
Erro ao acessar o domínio dos exemplos

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/doom-fire-algorithm#115]
Por algum motivo muito maluco que eu não estou conseguindo entender, quando acesso a URL:

https://filipedeschamps.github.io/doom-fire-algorithm/playground/1st-implementation-with-tables/

(note que está dentro do domínio do Github)

Ele redireciona para:

https://filipedeschamps.com.br/doom-fire-algorithm/playground/1st-implementation-with-tables

E dentro das configurações do repositório, ele mostra que está fazendo o deploy para o meu domínio (coisa que eu nunca configurei, tanto que todos os links no README eram para `github.io`

![image](https://user-images.githubusercontent.com/4248081/93234697-7533ab00-f731-11ea-835c-79f0d07bd529.png)

# Preciso de ajuda
Alguém faz ideia de como remover um domínio customizado? Eu não tenho nada no meu DNS que faça esse redirecionamento (e até porque, eu não controlo o DNS do `github.io`

**Comment by GRFreire** [comment]
Se eu não me engano o repo está pegando o arquivo CNAME ( que configura o domínio ) do repo do seu site https://github.com/filipedeschamps/filipedeschamps.github.io . A solução que encontrei seria remover o arquivo daquele repositório.

Link da solução que encontrei: https://github.com/isaacs/github/issues/1213#issuecomment-381864035

**Comment by filipedeschamps** [comment]
Caraca matou a pau @GRFreire vou testar agora 👍

**Comment by filipedeschamps** [comment]
Funcionou perfeitamente 😍 matou a pauuuuuu!!!! 🤝 Muito obrigado meu caro!!!!
