### ISSUE TITLE
Broken link: Faustão Edition

### ISSUE THREAD

**Issue by lgallindo** [filipedeschamps/doom-fire-algorithm#131]
https://filipedeschamps.com.br/doom-fire-algorithm/playground/ta-pegando-fogo-bixo/ gives me a 404 error

Is this online somewhere else?

**Comment by filipedeschamps** [comment]
Fala Lucas! Ótimo ponto, todos os links ali precisam ser alterados. Vou alterar, mas por enquanto, você pode acessar por: https://filipedeschamps.github.io/doom-fire-algorithm/playground/ta-pegando-fogo-bixo/
