### ISSUE TITLE
performance is horrible in firefox 64

### ISSUE THREAD

**Issue by ninja85a** [filipedeschamps/doom-fire-algorithm#3]
hey I've noticed on the demo it was looking alot slower then the gif on the github and it seemed to be running at 2FPS acording to the performance monitor in firefox 
https://www.dropbox.com/s/kazq1r0npd795hr/profile.json?dl=0
this is the log file from the performance tab in dev tools if you need anything else to help improve the performance I'll be glad to help 
my cpu is the R5 1600 and a RX 590 so it defiantly souldnt be my PC

**Comment by leocavalcante** [comment]
@ninja85a 
Can you benchmark both PR #1 and PR #2 ?
Cheers.

**Comment by lucianopf** [comment]
@ninja85a in my benchmarks FF performed way better than Chrome 🤔 (Even though I hate to admit that hehehe)

Chrome: 
<img width="225" alt="screen shot 2019-01-05 at 20 30 50" src="https://user-images.githubusercontent.com/8251208/50729882-e3d10080-1128-11e9-8420-e77494e34211.png">

FireFox (64):
<img width="130" alt="screen shot 2019-01-05 at 20 30 41" src="https://user-images.githubusercontent.com/8251208/50729885-efbcc280-1128-11e9-8f29-e72e52598a03.png">

**Comment by ninja85a** [comment]
huh thats werid that your getting alot higher FPS then me
it actually might be something wrong with my PC since on a discord I'm on someone has fine performance on firefox 64 no idea what tho

**Comment by filipedeschamps** [comment]
@ninja85a would you mind trying it out with the new experiments listed in the main README?

**Comment by filipedeschamps** [comment]
Closing this issue for now.
