### ISSUE TITLE
Why not use Canvas?

### ISSUE THREAD

**Issue by madureira** [filipedeschamps/doom-fire-algorithm#5]
Hi Filipe, congrats for your project man, is very cool!

By the way, have you thought about using Canvas instead of drawing inside a DIV? I'm saying this because, from experience, canvas performes better for this type of application. As you can see in **[this example](http://madureira.github.io/wolfenstein/)**, the frame rate is not very stable. I did a test refactoring part of my code to use canvas and the gain was very expressive.

Cheers.

**Comment by lucianopf** [comment]
I think that's definitely at his roadmap, using canvas and even other render engines!

As I understood his goal at first was to create a different way of rendering (to prove that it can work even with non expected methods) and also to be able to toggle the `debug` mode, which is amazing and works pretty well with the tables system.

Feel free to contribute to this project @madureira I'm pretty sure he'll be super happy to check a couple new ideas and implementations!

**Comment by filipedeschamps** [comment]
Closing this issue, since it was already implemented in some of the experiments.
