### ISSUE TITLE
React struggling to render the fire. HTML or Canvas.

### ISSUE THREAD

**Issue by felipepastor** [filipedeschamps/doom-fire-algorithm#61]
Is anyone facing a low performance when trying to render using React? I didn't change much of the code but react is struggling to have a nice perfomance with setInterval and the amount of pixels.

**Comment by filipedeschamps** [comment]
@felipepastor would you mind sending a PR with the experiment? It's slower compared to the table experiment?

**Comment by vinils** [comment]
same issue but not with react. i´m using pure javascript and change the code for a two dimensional
Any new on that?

**Comment by filipedeschamps** [comment]
Hi guys, I'm closing this issue do to inactivity, but have you seen this experiment? https://github.com/filipedeschamps/doom-fire-algorithm/tree/master/playground/react-implementation
