### ISSUE TITLE
I had an idea to cover all implementations in this repository :)

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/doom-fire-algorithm#9]
What do you think:

1. Rename this repository to `doom-fire-playground`
2. For each implementation, create an isolated and self-contained directory, for example
    - `original-implementation-with-table`
    - `render-engine-architecture`
    - `render-with-canvas`
    - `canvas-with-wind-control`
3. To avoid name clashing, we should use something like what we do with migrations files, for example:
    - `2019-01-04-original-implementation-with-table`
    - `2019-01-04-render-engine-architecture`
    - `2019-01-05-render-with-canvas`
    - `2019-01-17-canvas-with-wind-control`
4. Since you will have your own directory, you could add a `README.md` file if you wish to explain your implementation.

After this, I can even create a video about this playground or transform this repository into a tutorial to encourage developers to try something, since any experiment will be valid :)

Let's do this? 👍 

@leocavalcante @mccraveiro @AcePetrucci @brunooomelo @eduardosilvapereira @lucianopf @madureira @ninja85a

**Comment by filipedeschamps** [comment]
Done! At least, for a first step :)

![image](https://user-images.githubusercontent.com/4248081/51397258-f5060e00-1b27-11e9-890a-395c2db78c94.png)

**Comment by leocavalcante** [comment]
Cool!
You can drop `render-engine-architecture`
I'll PR `render-with-canvas-draw-rect`
Then @mccraveiro can PR `render-with-canvas-image-data`
And @eduardosilvapereira `render-with-canvas-and-wind-ctrl`
And so on
Sounds good?

**Comment by filipedeschamps** [comment]
Sounds good! What do you think to drop the `2019-01` suggested by me? Seems over engineering

**Comment by leocavalcante** [comment]
Agreed

**Comment by filipedeschamps** [comment]
Done!

**Comment by filipedeschamps** [comment]
I'm confused to why it's not opening:

https://filipedeschamps.github.io/doom-fire-algorithm/playground/1st-implementation-with-tables/

But it's opening:

https://filipedeschamps.github.io/doom-fire-algorithm/playground/1st-implementation-with-tables/index.html

**Comment by leocavalcante** [comment]
Both seams to be working here
![image](https://user-images.githubusercontent.com/183722/51399195-87a8ac00-1b2c-11e9-833b-2a2b7c64cbf7.png)

**Comment by filipedeschamps** [comment]
Wut!! I was receiving `404` probably was Github propagating the new data :)
